; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
env_default = nanoatmega328

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_flags = -Pusb
build_unflags = “-flto”
lib_deps = 
	fastled/FastLED@^3.10.5
	adafruit/RTClib@^2.1.4
	thomasfredericks/Bounce2@^2.72
	paulstoffregen/Encoder@^1.4.4

[env:native]
platform = native
test_framework = unity
lib_deps = 
	fastled/FastLED@^3.10.5
	adafruit/RTClib@^2.1.4
	thomasfredericks/Bounce2@^2.72
	paulstoffregen/Encoder@^1.4.4
